### ISSUE TITLE
Responsive About us Team Card 

### ISSUE THREAD

**Issue by tm2582001** [curiomind-e-learning/curiomind#19]
Hi, I am Tushar Mehta from GSSoC 22. I have found that team card in about us is
![issue](https://user-images.githubusercontent.com/90784567/156297963-c1b86337-27a7-4cb4-b3e3-fae202dd6a4b.png)

I want to improve this. Please assign me this issue.

**Comment by pratiksrivastava01** [comment]
I am a participant of GSSOC'22. I want to work on this issue. Can you please assign me?

**Comment by geekymeeky** [comment]
Go ahead @tm2582001
