### ISSUE TITLE
Hover effect in Navbar 

### ISSUE THREAD

**Issue by Anirban-1490** [curiomind-e-learning/curiomind#25]
there is already an issue on hovering but it dosen't cover navbar so i want to add it under GSSOC22

![Opera Snapshot_2022-03-03_094449_curiomind netlify app](https://user-images.githubusercontent.com/82874704/156495342-af9a33e1-c757-47ea-95b3-6e84977a87ed.png)

**Comment by Tiya0310** [comment]
I am a gssoc'22 participant, can I contribute to this issue?
