### ISSUE TITLE
Show/Hide Password while logging in and signing up

### ISSUE THREAD

**Issue by Siddhesh777** [curiomind-e-learning/curiomind#30]
**Is your feature request related to a problem? Please describe.**
Sometimes user may encounter a problem and  need to check what password he/she has entered.
In this project, there is no button which toggles showing/hiding password.

**Describe the solution you'd like**
I will make a button while will toggle the show/hide password using react useState hook.

**Additional context**
I am contributor at gssoc'22
Please assign this task to me

**Comment by Siddhesh777** [comment]
where are the css files ?

**Comment by KamalSinghKhanna** [comment]
Hi @Siddhesh777, there is already a button to show and hide passwords.

**Comment by Siddhesh777** [comment]
Yes @KamalSinghKhanna 
my PR only got merged😅
