### ISSUE TITLE
Add scroll to top button to main website 

### ISSUE THREAD

**Issue by Siddhesh777** [curiomind-e-learning/curiomind#58]
**Is your feature request related to a problem? Please describe.**
Sometimes User want to go to the top of the page after scrolling a lot.

**Describe the solution you'd like**
I want to make a button which will take a user to the top of the page.

**Additional context**
I am contributor at GSSOC'22.
Please assign this task to me.

![1](https://user-images.githubusercontent.com/77476772/160882749-ea4d7a4c-1063-4651-b25f-7e73abfce61a.png)

**Comment by geekymeeky** [comment]
Duplicate #57
