### ISSUE TITLE
Redesign navbar and create hamburger

### ISSUE THREAD

**Issue by Adhetya** [curiomind-e-learning/curiomind#61]
**Is your feature request related to a problem? Please describe.**
Navbar is responsive in mobile view however, it occupies a lot of space when it opens not giving a good UI

**Describe the solution you'd like**
I would like to embed it in a hamburger menu which on click reveals the navigation links to make UI more neat

**Describe alternatives you've considered**

**Additional context**
<img width="1440" alt="Screenshot 2022-04-05 at 11 28 44 AM" src="https://user-images.githubusercontent.com/20537150/161688346-90e47b57-b323-4315-842f-e08d8ce58be0.png">

**Comment by geekymeeky** [comment]
@Adhetya Go ahead
